### ISSUE TITLE
Terminal.geometry does not exist

### ISSUE THREAD

**Issue by corwin-of-amber** [risacher/tty.js#13]
I am guessing this property used to exist on some older version of xterm.js.

However now this line produces an error, preventing the terminal from opening.
https://github.com/risacher/ttyx/blob/e62c6e18c3eff4208036a09562b7b7eb2de74d1d/static/ttyx-client.js#L309

I am using `xterm@3.14.5` as listed in `package.json`.

**Comment by risacher** [comment]
This didn't affect me because I set it in ~/.ttyx/config.json, which is okay but there needs to be some default set somewhere.

**Comment by risacher** [comment]
BTW, cool github username, @corwin-of-amber

**Comment by corwin-of-amber** [comment]
@risacher LOL!

**Comment by risacher** [comment]
Fixed by 1559548
